version: '3.8'

services:
  atlas:
    container_name: AtlasEvaluation-runtime
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    hostname: AtlasEvaluation
    tty: true
    stdin_open: true
    shm_size: 100g
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/../nnUNet:/nnunet
    environment:
      - MODEL_PREDICTION_DIR=/nnunet/outputs/output_Task500_ATLAS_ATLAS_500EP
    entrypoint: python3 convert_to_BIDS.py