version: '3.8'

services:
  eval:
    container_name: MICCAI-ISELS-evaluation-runtime
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    shm_size: 100g
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/../nnUNet:/nnunet
    environment:
      - CHECK_CRC=False
      - MODEL_PREDICTION_DIR=/nnunet/outputs/output_Task505_ATLAS_ATLAS_500EP
    entrypoint: python3 convert_to_BIDS.py