version: '3.8'

services:
  AtlasChallenge:
    container_name: AtlasEvaluation-runtime
    hostname: AtlasEvaluation
    image: atlas-challenge
    tty: true
    stdin_open: true
    shm_size: 64G
    volumes:
      - /root/projects/atlas2_grand_challenge:/root/workspace/
      - /root/nnUNet/outputs:/root/workspace/outputs
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MODEL_PREDICTION_DIR=<YOUR-OUTPUT-DIR>
    entrypoint: python3 convert_to_BIDS.py